apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
images:
- name: gcr.io/YOUR_GCP_PROJECT_ID/api-gateway
  newTag: "dev"
- name: gcr.io/YOUR_GCP_PROJECT_ID/household-service
  newTag: "dev"
- name: gcr.io/YOUR_GCP_PROJECT_ID/planner-service
  newTag: "dev"
- name: gcr.io/YOUR_GCP_PROJECT_ID/translation-service
  newTag: "dev"
- name: gcr.io/YOUR_GCP_PROJECT_ID/feedback-service
  newTag: "dev"
- name: gcr.io/YOUR_GCP_PROJECT_ID/scheduler-service
  newTag: "dev"
